service: swapi-indra
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
      - arn:aws:dynamodb:sa-east-1:862454797065:table/PersonasTable

functions:
  getPeople:
    handler: src/router.getPeople
    events:
      - httpApi:
          path: /personas
          method: get

resources:
  Resources:
    PersonasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonasTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH